# Generated by Django 3.2.7 on 2021-09-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('ext', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=256)),
                ('size', models.FloatField(default=0)),
            ],
        ),
    ]
