# Generated by Django 3.2.5 on 2021-12-31 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_auto_20211231_1652'),
        ('Order', '0002_alter_order_promotion'),
        ('Goods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserInfo.shop'),
            preserve_default=False,
        ),
    ]
