# Generated by Django 3.2.5 on 2022-01-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_auto_20211231_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='discount',
            field=models.FloatField(default=100),
        ),
    ]
