# Generated by Django 3.2.5 on 2021-12-31 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('ext', models.CharField(max_length=20)),
                ('file_path', models.TextField()),
                ('file_size', models.FloatField(default=0)),
            ],
        ),
    ]
