# Generated by Django 3.2.5 on 2021-12-31 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Goods', '__first__'),
        ('UserInfo', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_pay', models.FloatField(default=0)),
                ('status', models.IntegerField()),
                ('abstract_pay', models.FloatField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goods', models.ManyToManyField(to='Goods.Goods')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Goods.promotion')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserInfo.shop')),
            ],
        ),
    ]
