# Generated by Django 3.2.5 on 2022-01-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0002_auto_20211231_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='autoAccept',
            field=models.BooleanField(default=True),
        ),
    ]
