# Generated by Django 3.2.7 on 2021-09-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(choices=[(1, 'Consumer'), (2, 'Business')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('age', models.IntegerField(default=18)),
                ('money', models.FloatField(default=0)),
                ('sex', models.CharField(max_length=2)),
                ('abstract_money', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.group')),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.attachment')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=200)),
                ('vote', models.IntegerField(default=0)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.attachment')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
