# Generated by Django 3.2.7 on 2021-09-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('goods', models.ManyToManyField(to='goods.Coffe')),
            ],
        ),
    ]
